/**
 * Preset designs the editor can start from. Each template is just a frozen
 * CanvasState (sans selection). Adding a new one is a literal here — no
 * code path in the editor needs to know about it.
 *
 * Includes the originals: the Apex-Crown hiring card and the SpaceX-collab
 * lockup. Both were the standalone /social/{hiring-bd,spacex} pages before
 * the editor existed; their visual recipes survive as editable starting
 * points so we never lose them.
 */

import type { CanvasState } from "./types";
import { DEFAULT_GRADIENT_PARAMS } from "./types";

let _id = 0;
const layerId = (): string => `l${++_id}`;

export interface Template {
  id: string;
  name: string;
  state: Omit<CanvasState, "selectedLayerId">;
}

export const TEMPLATES: Template[] = [
  {
    id: "blank",
    name: "Blank",
    state: {
      format: "x",
      backgroundId: "black",
      backgroundColors: null,
      backgroundOpacity: 1,
      gradientParams: { ...DEFAULT_GRADIENT_PARAMS },
      layers: [],
    },
  },
  {
    id: "hiring-bd",
    name: "Hiring · Apex Crown",
    state: {
      format: "x",
      backgroundId: "aurora",
      backgroundColors: null,
      backgroundOpacity: 1,
      gradientParams: { ...DEFAULT_GRADIENT_PARAMS },
      layers: [
        {
          id: layerId(),
          type: "image",
          src: "/tier/apex-cutout.png",
          x: 0.52,
          y: 0.32,
          width: 0.4,
          height: 0.6,
          opacity: 1,
          rotation: 8,
          filter:
            "saturate(1.45) brightness(0.88) hue-rotate(22deg) contrast(1.08) drop-shadow(0 0 36px rgba(47,123,255,0.55)) drop-shadow(0 0 12px rgba(47,123,255,0.45))",
          featherRadius: 0.2,
        },
        {
          id: layerId(),
          type: "text",
          text: "Now hiring",
          font: "sans",
          size: 0.03,
          weight: 500,
          tracking: 0.18,
          lineHeight: 1,
          color: "rgba(255,255,255,0.62)",
          uppercase: true,
          align: "center",
          shadow: true,
          glow: null,
          x: 0.5,
          y: 0.78,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Business Developers",
          font: "sans",
          size: 0.105,
          weight: 500,
          tracking: -0.035,
          lineHeight: 1.02,
          color: "#ffffff",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.83,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Velocity",
          font: "brand",
          size: 0.06,
          weight: 600,
          tracking: -0.035,
          lineHeight: 1,
          color: "#ffffff",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.94,
          opacity: 1,
          rotation: 0,
        },
      ],
    },
  },
  {
    id: "spacex-collab",
    name: "SpaceX · Collab",
    state: {
      format: "x",
      backgroundId: "threads",
      backgroundColors: null,
      backgroundOpacity: 1,
      gradientParams: { ...DEFAULT_GRADIENT_PARAMS },
      layers: [
        {
          id: layerId(),
          type: "image",
          src: "/social/wordmarks/spacex.svg",
          x: 0.34,
          y: 0.48,
          width: 0.22,
          height: 0.04,
          opacity: 1,
          rotation: 0,
          filter: "",
          featherRadius: 0,
        },
        {
          id: layerId(),
          type: "line",
          orientation: "vertical",
          length: 0.19,
          thickness: 1,
          color: "rgba(255,255,255,0.5)",
          fade: true,
          x: 0.5,
          y: 0.48,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Velocity",
          font: "brand",
          size: 0.126,
          weight: 600,
          tracking: -0.02,
          lineHeight: 1,
          color: "#ffffff",
          uppercase: false,
          align: "left",
          shadow: false,
          glow: null,
          x: 0.62,
          y: 0.48,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Now tradable on Velocity",
          font: "sans",
          size: 0.04,
          weight: 500,
          tracking: -0.005,
          lineHeight: 1.1,
          color: "rgba(255,255,255,0.78)",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.88,
          opacity: 1,
          rotation: 0,
        },
      ],
    },
  },
  {
    id: "collab",
    name: "Generic Collab",
    state: {
      format: "x",
      backgroundId: "custom-gradient",
      backgroundColors: null,
      backgroundOpacity: 1,
      gradientParams: { ...DEFAULT_GRADIENT_PARAMS },
      layers: [
        {
          id: layerId(),
          type: "text",
          text: "Velocity",
          font: "brand",
          size: 0.1,
          weight: 600,
          tracking: -0.025,
          lineHeight: 1,
          color: "#ffffff",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.36,
          y: 0.5,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "×",
          font: "sans",
          size: 0.06,
          weight: 300,
          tracking: 0,
          lineHeight: 1,
          color: "rgba(255,255,255,0.45)",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.5,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Partner",
          font: "brand",
          size: 0.1,
          weight: 600,
          tracking: -0.025,
          lineHeight: 1,
          color: "#ffffff",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.64,
          y: 0.5,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Protected by Velocity",
          font: "sans",
          size: 0.028,
          weight: 500,
          tracking: -0.005,
          lineHeight: 1,
          color: "rgba(255,255,255,0.7)",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.9,
          opacity: 1,
          rotation: 0,
        },
      ],
    },
  },
  {
    id: "announcement",
    name: "Announcement",
    state: {
      format: "x",
      backgroundId: "lightrays",
      backgroundColors: null,
      backgroundOpacity: 1,
      gradientParams: { ...DEFAULT_GRADIENT_PARAMS },
      layers: [
        {
          id: layerId(),
          type: "text",
          text: "Announcing",
          font: "sans",
          size: 0.028,
          weight: 500,
          tracking: 0.22,
          lineHeight: 1,
          color: "rgba(255,255,255,0.5)",
          uppercase: true,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.4,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Headline goes here",
          font: "sans",
          size: 0.092,
          weight: 600,
          tracking: -0.035,
          lineHeight: 1.04,
          color: "#ffffff",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.5,
          opacity: 1,
          rotation: 0,
        },
        {
          id: layerId(),
          type: "text",
          text: "Velocity",
          font: "brand",
          size: 0.06,
          weight: 600,
          tracking: -0.035,
          lineHeight: 1,
          color: "#ffffff",
          uppercase: false,
          align: "center",
          shadow: false,
          glow: null,
          x: 0.5,
          y: 0.88,
          opacity: 1,
          rotation: 0,
        },
      ],
    },
  },
];

export const TEMPLATE_BY_ID: Record<string, Template> = Object.fromEntries(
  TEMPLATES.map((t) => [t.id, t]),
);
